import { User, Journal, Run, ScheduledWorkout } from "@/types/modelTypes";

export const users: User[] = [
    { id: 1, name: "Alice" },
    { id: 2, name: "Bob" },
    { id: 3, name: "Charlie" },
];

export const journals: Journal[] = [
    {
        id: 1,
        userId: 1,
        title: "Alice's Journal",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
    },
    {
        id: 2,
        userId: 2,
        title: "Bob's Journal",
        startDate: "2022-01-01",
        endDate: "2022-12-31",
    },
];

export const runs: Run[] = [
    {
        id: 1,
        userId: 1,
        journalId: 1,
        title: "Morning Run",
        type: "Long",
        date: "2024-01-01 06:00:00",
        notes: "Easy morning run",
        distance: 10000,
        duration: 3600,
        pace: 360,
        heartRate: 150,
        effort: 5,
        equipmentIds: [1],
    },
    {
        id: 2,
        userId: 2,
        journalId: 2,
        title: "Evening Run",
        type: "Tempo",
        date: "2022-01-02 18:00:00",
        notes: "Evening tempo run",
        distance: 5000,
        duration: 1800,
    },
    {
        id: 3,
        userId: 1,
        journalId: 1,
        title: "Afternoon Run",
        type: "Interval",
        date: "2024-01-04 15:00:00",
        notes: "Afternoon interval run",
        distance: 8000,
        duration: 2400,
    },
    {
        id: 4,
        userId: 1,
        journalId: 1,
        title: "Run",
        type: "Easy run",
        date: "2024-01-04 15:00:00",
        distance: 8000,
        duration: 2400,
    },
    {
        id: 5,
        userId: 1,
        journalId: 1,
        title: "Run",
        type: "Easy run",
        date: "2024-01-07 15:00:00",
        distance: 8000,
        duration: 2400,
    },
    {
        id: 6,
        userId: 1,
        journalId: 1,
        title: "Run",
        type: "Easy run",
        date: "2024-01-09 15:00:00",
        distance: 10000,
        duration: 2400,
    },
    {
        id: 7,
        userId: 1,
        journalId: 1,
        title: "Run",
        type: "Easy run",
        date: "2024-01-11 15:00:00",
        distance: 5000,
        duration: 1800,
    },
    {
        id: 8,
        userId: 1,
        journalId: 1,
        title: "Run",
        type: "Easy run",
        date: "2024-01-14 15:00:00",
        distance: 8000,
        duration: 2400,
    },
];

export const scheduledWorkouts: ScheduledWorkout[] = [
    {
        id: 1,
        userId: 1,
        journal_id: 1,
        title: "Morning Run",
        date: "2024-01-01 06:00:00",
        type: "Long",
        description: "Easy morning run",
        distance: 10000,
    },
    {
        id: 2,
        userId: 2,
        journal_id: 2,
        title: "Evening Run",
        date: "2022-01-02 18:00:00",
        type: "Tempo",
        description: "Evening tempo run",
        distance: 5000,
    },
    {
        id: 3,
        userId: 1,
        journal_id: 1,
        title: "Afternoon Run",
        date: "2024-01-04 15:00:00",
        type: "Interval",
        description: "Afternoon interval run",
        distance: 8000,
    },
];

export const equipment = [];
